twig:
    default_path: '%kernel.project_dir%/templates'
    date:
        format: 'F j, Y H:i'
        interval_format: '%d days'
        timezone: 'Europe/Paris'
    number_format:
        decimals: 0
        decimal_point: .
        thousands_separator: ','

when@test:
    twig:
        strict_variables: true
